#!/usr/bin/env bash
#Install haproxy and configurate both servers

apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 22760-web-01 54.237.116.10:80 check\n\tserver 22760-web-02 54.89.29.237:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
