#!/usr/bin/env bash
#Install haproxy and configurate both servers


apt-get -y update
apt-get -y install haproxy=1.6.*

# Backup the original haproxy.cfg
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend merga-wolde.tech
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 54.237.116.10:80 check
    server web-02 54.89.29.237:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAProxy service to apply changes
service haproxy restart